/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        ARDUINOTJ2560EXT_CATEGORY: 'MUGEN',
        ARDUINOTJ2560EXT_PLAYSOUND: 'on board buzzer play sound with frequency %1 Hz for %2 second',
        ARDUINOTJ2560EXT_PLAYTONEFORBEAT: 'on board buzzer play tone %1 for %2 beat',
        ARDUINOTJ2560EXT_SETTEMPO: 'set on board buzzer tempo to (bpm) %1',
        ARDUINOTJ2560EXT_PLAYRINGTONE: 'on board buzzer play ringtone %1',
        ARDUINOTJ2560EXT_CONNECTION: 'connection',
        ARDUINOTJ2560EXT_DISCONNECTION: 'disconnet',
        ARDUINOTJ2560EXT_DIDI: 'button pushed',
        ARDUINOTJ2560EXT_MODE1: 'mode1',
        ARDUINOTJ2560EXT_MODE2: 'mode2',
        ARDUINOTJ2560EXT_MODE3: 'mode3',
        ARDUINOTJ2560EXT_SURPRISE: 'surprise',
        ARDUINOTJ2560EXT_OHOOH: 'OhOoh',
        ARDUINOTJ2560EXT_OHOOH2: 'OhOoh2',
        ARDUINOTJ2560EXT_CUDDLY: 'cuddly',
        ARDUINOTJ2560EXT_SLEEPING: 'sleeping',
        ARDUINOTJ2560EXT_HAPPY: 'happy',
        ARDUINOTJ2560EXT_SUPERHAPPY: 'super happy',
        ARDUINOTJ2560EXT_HAPPYSHORT: 'happy short',
        ARDUINOTJ2560EXT_SAD: 'sad',
        ARDUINOTJ2560EXT_CONFUSED: 'confused',
        ARDUINOTJ2560EXT_FART1: 'fart1',
        ARDUINOTJ2560EXT_FART2: 'fart2',
        ARDUINOTJ2560EXT_FART3: 'fart3',
        ARDUINOTJ2560EXT_ONBOARDDRIVERRUN: 'on board motor driver %1 run %2 speed %3',
        ARDUINOTJ2560EXT_ONBOARDDRIVERSTOP: 'on board motor driver %1 stop',
        ARDUINOTJ2560EXT_FORWARD: 'counter-clockwise',
        ARDUINOTJ2560EXT_BACK: 'clockwise',
        ARDUINOTJ2560EXT_ONBOARDENCODERREAD: 'read on board encoder %1 value',
        ARDUINOTJ2560EXT_ONBOARDENCODERRESET: 'reset on board encoder %1 value',
        ARDUINOTJ2560EXT_BLUETOOTHPRINT: 'bluetooth send %1 %2',
        ARDUINOTJ2560EXT_WARP: 'warp',
        ARDUINOTJ2560EXT_NOWARP: 'no-warp',
        ARDUINOTJ2560EXT_BLUETOOTHAVAILABLE: 'bluetooth available data length',
        ARDUINOTJ2560EXT_BLUETOOTHREADABYTE: 'bluetooth read a byte',
        ARDUINOTJ2560EXT_IRRECIVE: 'read ir remoter data',
        ARDUINOTJ2560EXT_ISIRPRESS: 'ir remoter channel %1 key %1 is press?',
        ARDUINOTJ2560EXT_POWER: 'power',
        ARDUINOTJ2560EXT_SETSERVO: 'set %1 servo angle %2',
        ARDUINOTJ2560EXT_SETTIME: 'delay %1 us'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        ARDUINOTJ2560EXT_CATEGORY: 'MUGEN',
        ARDUINOTJ2560EXT_PLAYSOUND: '板载蜂鸣器以频率 %1 Hz 播放声音持续 %2 秒',
        ARDUINOTJ2560EXT_PLAYTONEFORBEAT: '板载蜂鸣器播放音调 %1 持续 %2 节拍',
        ARDUINOTJ2560EXT_SETTEMPO: '设置板载蜂鸣器节奏为 (bpm) %1',
        ARDUINOTJ2560EXT_PLAYRINGTONE: '板载蜂鸣器播放铃声 %1',
        ARDUINOTJ2560EXT_CONNECTION: '连接',
        ARDUINOTJ2560EXT_DISCONNECTION: '断开',
        ARDUINOTJ2560EXT_DIDI: '按键按下',
        ARDUINOTJ2560EXT_MODE1: '模式1',
        ARDUINOTJ2560EXT_MODE2: '模式2',
        ARDUINOTJ2560EXT_MODE3: '模式3',
        ARDUINOTJ2560EXT_SURPRISE: '惊讶',
        ARDUINOTJ2560EXT_OHOOH: '哦哦',
        ARDUINOTJ2560EXT_OHOOH2: '哦哦2',
        ARDUINOTJ2560EXT_CUDDLY: '可爱',
        ARDUINOTJ2560EXT_SLEEPING: '正在睡觉',
        ARDUINOTJ2560EXT_HAPPY: '开心',
        ARDUINOTJ2560EXT_SUPERHAPPY: '非常开心',
        ARDUINOTJ2560EXT_HAPPYSHORT: '开心短',
        ARDUINOTJ2560EXT_SAD: '难过',
        ARDUINOTJ2560EXT_CONFUSED: '困惑',
        ARDUINOTJ2560EXT_FART1: '放屁1',
        ARDUINOTJ2560EXT_FART2: '放屁2',
        ARDUINOTJ2560EXT_FART3: '放屁3',
        ARDUINOTJ2560EXT_ONBOARDDRIVERRUN: '驱动 %1 板载电机 %2 方向以速度 %3 旋转',
        ARDUINOTJ2560EXT_ONBOARDDRIVERSTOP: '驱动板载电机 %1 停止旋转',
        ARDUINOTJ2560EXT_FORWARD: '逆时针',
        ARDUINOTJ2560EXT_BACK: '顺时针',
        ARDUINOTJ2560EXT_ONBOARDENCODERREAD: '读取板载编码器 %1 数值',
        ARDUINOTJ2560EXT_ONBOARDENCODERRESET: '重置板载编码器 %1 数值',
        ARDUINOTJ2560EXT_BLUETOOTHPRINT: '蓝牙模块发送 %1 %2',
        ARDUINOTJ2560EXT_WARP: '换行',
        ARDUINOTJ2560EXT_NOWARP: '不换行',
        ARDUINOTJ2560EXT_BLUETOOTHAVAILABLE: '蓝牙模块可用数据长度',
        ARDUINOTJ2560EXT_BLUETOOTHREADABYTE: '蓝牙模块读取一个字节',
        ARDUINOTJ2560EXT_IRRECIVE: '读取红外遥控数据',
        ARDUINOTJ2560EXT_ISIRPRESS: '红外遥控器通道 %1 按键 %2 被按下?',
        ARDUINOTJ2560EXT_POWER: '电源',
        ARDUINOTJ2560EXT_SETSERVO: '设置 %1 舵机角度 %2',
        ARDUINOTJ2560EXT_SETTIME: '等待 %1 微秒'
    });
    return Blockly;
}

exports = addMsg;
